# Generated by Django 2.2.14 on 2020-08-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0296_remove_userprofile_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='logo_source',
            field=models.CharField(choices=[('D', 'Default to Zulip'), ('U', 'Uploaded by administrator')], default='U', max_length=1),
        ),
    ]
